version: '3.11.1'

services:
  web:
    build:
      context: .
    container_name: "task_web"
    restart: always
    command: bash ./entrypoint.sh
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    networks:
      - my_network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: "task_db"
    restart: always
    environment:
      POSTGRES_DB: task_4dx
      POSTGRES_USER: server
      POSTGRES_PASSWORD: 123
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:

volumes:
  media_volume:
  db_data:
